# In the Makefile, this is a comment

#runme: bisect2.o  xsinx.o 
#	g++ bisect2.o  xsinx.o  -o run -lm 

runme: golden.o fun.o 
	g++ golden.o fun.o -o run -lm 


cleanme:
	rm *.o

#tar cvzf
#problem4.tgz BISECTMAKE
